version: "3.9"
services:
  backend:
    container_name: blog_220228
    build: .
    volumes:
      - .:/blog_220228
    ports:
      - 8000:8000
    depends_on:
      - db_blog_220228

  db_blog_220228:
    container_name: db_blog_220228
    image: postgres
    restart: always
    volumes:
      - .dbdata:/var/lib/db_blog_220228
    ports:
      - 5451:5432